### ISSUE TITLE
Chart not updated

### ISSUE THREAD

**Issue by Newan** [GoogleWebComponents/google-chart#51] opened 2015-06-17 13:11 UTC
I want to refresh my Chart after X seconds, like the Demo page.
chart is embbed in polymer 1.0 (Staterkit)
```
  <script>
    function getRandomValue() {
      return Math.random() * 10;
    }
    window.setInterval(function() {
      var chart = document.getElementById('mutating_chart');
      chart.rows = [ ["Col1", getRandomValue()],
                    ["Col2", getRandomValue()],
                    ["Col3", getRandomValue()] ];
    }, 3000);
  </script>
```
But the chart does not redraw.
The code is from the demo page, with the spaces by rows for polymer….what is wrong?

**Comment by jhrdka** [comment] 2015-06-23 10:40
I also had a problem with combination **google-chart** + **Polymer Starter Kit**. I tried to insert simple

    <google-chart
      cols='[{"label": "Data", "type": "string"},{"label": "Value", "type": "number"}]'
      rows='[["Something", 1]]'>
    </google-chart>

but nothing showed. It started to work after I moved it outside of the main `<template is="dom-bind" id="app">`, which is not a very good solution I guess.

**Comment by SmokyBob** [comment] 2015-06-23 22:32
@jhrdka your problem is caused by the fact that the following line:
`rows='[["Something", 1]]'`
is interpreted as a databinding ((open issue on Polymer Repo)[https://github.com/Polymer/polymer/issues/1734]), if you change as specified in the following line
`rows='[ ["Something", 1] ]'` 
aka. add a space between the [[ and ]] should work as intented. 

P.S. docs for the chart are not updated and use the [[ for instead of [ [

**Comment by wesalvaro** [comment] 2016-03-15 03:52
I'm not able to reproduce the issue, so I'm going to close it.
@Newan please re-open if you are still having the issue and provide a link to an example of the problem.

**Closed by wesalvaro** 2016-03-15 03:52 UTC
