### ISSUE TITLE
No redraw after clearing rows/cols property

### ISSUE THREAD

**Issue by aquadisco** [GoogleWebComponents/google-chart#106] opened 2016-04-20 01:27 UTC
Might be an issue on my end, but i've been unable to get the chart object (using as a DataTable) to redraw itself as ...i guess ;nothing'?... after i clear out the row and column data attributes.  I've tried this two ways.

`            <google-chart
              id="activeprjtable"
              type='table'
              options='{"sortColumn": 7, "allowHtml": true}'
              cols='{{tablecols}}'
              rows='{{activetablerows}}'></google-chart>`

I've just set `tablecols` and `activetablerows` to a zero element array ('`[]`).  I've also used `this.splice` to remove all elements since that ought to make polymer look at the property and do any necessary updates?

Finally, i've tried to call `this.$.activeprjtable.drawChart()`directly after zeroing out the arrays..but that doesn't work either.

Seems like doing this should cause the table to disappear.

**Comment by wesalvaro** [comment] 2016-04-28 06:00
What version are you using?
I think this is a bug that was fixed in #83.

**Comment by aquadisco** [comment] 2016-04-28 15:15
I've got 0.1.4 installed currently

**Comment by yglodt** [comment] 2016-06-07 13:35
Maybe this is related... The following code does not work either, using the latest google-chart.html:

```
<script type="text/javascript">
	var app = document.querySelector("template#app");
	app.addEventListener('dom-change', function() {

        var chart = document.getElementById("c1");
        chart.cols = [{label: "Categories", type: "string"}, {label: "Value", type: "number"}];

        chart.rows = [["Category 1", 1.0], ["Category 2", 1.1]];
        chart.rows.push(["Category 3", Math.random() * 2]);
        chart.rows.push(["Category 4", Math.random() * 2]);
        chart.rows.push(["Category 5", Math.random() * 2]);

        // so far so good, at this point of time the chart is displayed with 5 values.

        window.setTimeout(function() {
            chart.rows.push(["Category 6", Math.random() * 2]); // has no effect ...
            chart.drawChart(); // still no effect ...
        }, 1000);

    });

</script>

```

**Comment by wesalvaro** [comment] 2016-06-16 11:46
I don't think that calling native push on an object in Polymer ever works.

**Comment by wesalvaro** [comment] 2016-07-20 07:45
So, I think the issue is that you need to call Polymer's `push` method to let Polymer know about the change to the rows. Without that, no change is known and the proper conversion of `rows -> DataTable` is not done. That means even the call to `drawChart` would have no effect.

**Closed by wesalvaro** 2016-07-20 07:45 UTC
Labels: bug
