### ISSUE TITLE
Chart rendering issues when using bootstrap tab resource

### ISSUE THREAD

**Issue by vitorfavila** [GoogleWebComponents/google-chart#54] opened 2015-07-17 18:44 UTC
When I'm using the Bootstrap tab resource, initial tab works fine, but in other tabs, Google Chart draws the legend and the vertical title out of alignment, and the tables do not respect the width set on table options.

I'm considering a bug, cause I've tried without tabs, and worked fine.

This is the initial tab, render is fine.
![firsttab](https://cloud.githubusercontent.com/assets/13317940/8754512/69c1336c-2c9a-11e5-9eb5-e504bde315db.jpg)

Second tab, problems marked in red.
![secondtab](https://cloud.githubusercontent.com/assets/13317940/8754513/69c195d2-2c9a-11e5-9f13-2aa0c185fdc4.jpg)

**Comment by ebidel** [comment] 2015-07-19 09:11
Seems more like a problem with using Bootstrap tabs and the element. Can you please post a reproducible test case that shows the bug.

**Comment by vitorfavila** [comment] 2015-07-20 16:29
ebidel, I think you're right. When width is set in chart options, it works, but if the width is set on a DIV style, the chart render in a small size.

Check this jsfiddle, the main tab is ok, the second tab have width set on js, and the third tab have width set on css html.

https://jsfiddle.net/dd3eo7xd/

**Comment by ebidel** [comment] 2015-07-22 20:21
IIRC, this makes sense. The google chart needs an explicit width to render its svg container. So I think you'll need to set one on each tab.

**Comment by wesalvaro** [comment] 2016-03-15 04:39
I'm going to close this issue since it seems to be solved and has been open for a while.

Please feel free to re-open!

**Closed by wesalvaro** 2016-03-15 04:39 UTC
