### ISSUE TITLE
org chart is broken

### ISSUE THREAD

**Issue by Hareesh-kumar-kuruba** [GoogleWebComponents/google-chart#205] opened 2017-11-22 11:39 UTC
I had google-chart of type orgchart in my polymer project.It was working fine in my 1.x polymer project. While updating my polymer project to 2.0 it was broken. I tried the example given in demo in new project, there also it is broken. It looks like the below pic where connectors are missing
![screencapture-127-0-0-1-8000-chart-test-html-1511350086208](https://user-images.githubusercontent.com/26483710/33125668-6cfe8950-cfa7-11e7-967d-eba4ac21086e.png)

And my code is 
```
`<!doctype html>
<!-- Copyright (c) 2014 Google Inc. All rights reserved. -->
<html>
<head>
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, user-scalable=yes">
    <title>google-chart Demo</title>

    <script src="bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="bower_components/promise-polyfill/promise-polyfill-lite.html">
    <link rel="import" href="bower_components/google-chart/google-chart.html">
    <style>
        code {
            color: #007000;
        }

        google-chart {
            height: 300px;
            width: 400px;
        }
    </style>

</head>
<body>


<p>Here's a organization chart:</p>

<google-chart
        id="org-chart",
        type="org",
        options='{"allowHtml": "true"}'
        cols='[{"label": "Name", "type": "string"},{"label":"Manager", "type":"string"},{"label":"ToolTip", "type":"string"}]'
        rows='[[{"v":"Mike", "f":"Mike<div style=\"color:red; font-style:italic\">President</div>"},
            "", "The President"],
            [{"v":"Jim", "f":"Jim<div style=\"color:red; font-style:italic\">Vice President</div>"},
            "Mike", "VP"],
            ["Alice", "Mike", ""],
            ["Bob", "Jim", "Bob Sponge"],
            ["Carol", "Bob", ""]]'>
</google-chart>

</body>
</html>`
```

**Comment by wesalvaro** [comment] 2018-01-12 03:34
This looks like a duplicate of #138 which would be fixed by a fix for #26.
I have a fix in #204 but it essentially changes everything, so I need a good reviewer (I also need to add some more tests). I believe that #204 is a much more Polymer-y version that has a bunch of needed changes/refactors. If you want to take a look, that'd be great.

**Closed** 2018-01-12 03:37 UTC
Labels: bug, duplicate
