### ISSUE TITLE
HTML tooltips are not styled correctly

### ISSUE THREAD

**Issue by rslawik** [GoogleWebComponents/google-chart#206] opened 2018-01-02 11:15 UTC
HTML tooltips in `<google-chart>` using Polymer 2 and ShadowDOM are not positioned correctly and their styles are missing.

```javascript
chart.options = {
  tooltip: {
    isHtml: true
  }
}
```

![image](https://user-images.githubusercontent.com/7468393/34482149-2917bece-efae-11e7-8994-f3661c53826d.png)

**Comment by wesalvaro** [comment] 2018-01-12 03:33
This looks like a duplicate of #138 which would be fixed by a fix for #26.
I have a fix in #204 but it essentially changes everything, so I need a good reviewer (I also need to add some more tests). I believe that #204 is a much more Polymer-y version that has a bunch of needed changes/refactors. If you want to take a look, that'd be great.

**Closed by wesalvaro** 2018-01-12 03:33 UTC
Labels: bug, duplicate
