### ISSUE TITLE
Google table chart default styles are not applied.

### ISSUE THREAD

**Issue by ThePlenkov** [GoogleWebComponents/google-chart#207] opened 2018-01-04 20:48 UTC
Hi,

I just decided to try polymer with google table chart.

What a disappointment to find it without any style.

![image](https://user-images.githubusercontent.com/6381507/34583606-ace8f2cc-f198-11e7-9473-6ffb27f85e89.png)

What I did - I just cloned this repository and served with polymer.

What is interesting, here it works fine:
https://elements.polymer-project.org/bower_components/google-chart/demo/index.html

May be it is polymer issue?

**Comment by wesalvaro** [comment] 2018-01-12 03:34
This looks like a duplicate of #138 which would be fixed by a fix for #26.
I have a fix in #204 but it essentially changes everything, so I need a good reviewer (I also need to add some more tests). I believe that #204 is a much more Polymer-y version that has a bunch of needed changes/refactors. If you want to take a look, that'd be great.

**Closed** 2018-01-12 03:35 UTC
Labels: bug, duplicate
