### ISSUE TITLE
Multiple calls to google.charts.load() not allowed.

### ISSUE THREAD

**Issue by fmauNeko** [GoogleWebComponents/google-chart#115] opened 2016-06-09 08:43 UTC
Hello,

There's a regression that appeared with the release of version 1.0.5 (Merge of #114), it is not possible to call back `google.charts.load()` to load another package.

The demo page itself is broken starting with the table, which displays `Error: google.charts.load() cannot be called more than once with version 45 or earlier.`

Switching the version from `'current'` to `'upcoming'` triggers another error, `TypeError: ctor is not a constructor`, at google-chart.html:69 in chartConstructor(), when trying to create a chart from the second package. After inspecting, the Promise generated by the second load() call doesn't include the requested chart.

**Comment by fmauNeko** [comment] 2016-06-09 10:12
After further inspection, I think it's because multiple getChartPackage() calls start multiple load() calls, and when the first one is done, it calls the onLoadCallback resolving the promise for all parallel calls, so as I call it for 'corecharts' first then 'table', the promise for 'table' is resolved when 'corecharts' finishes loading, thus resolving the Promise without the Table elements.

**Comment by cbelden** [comment] 2016-06-09 16:35
This is a known limitation with the new loading API: https://developers.google.com/chart/interactive/docs/basic_load_libs#basic-library-loading (search the page for "limitations")

I can definitely see how this will break a lot of people; easiest case I can think of is just having two google-chart component instances on a page (haven't actually tested this).

**Comment by fmauNeko** [comment] 2016-06-09 17:03
That's actually what I'm already doing, I have a pie chart component then a table component, which doesn't work.
Code is something like this (forgot to push before leaving work.)
`
<google-chart
        type='pie'
        options='{"title": "Origine des réservations web", "pieHole": 0.4}'
        data='/api/origin'>
</google-chart>
<google-chart
        type='table'
        options='{"title": "Origine des réservations web"'
        data='/api/origin'>
</google-chart>
`
Pie is in the corecharts package, table in the table package, the pie loads, but not the table.

**Comment by ebidel** [comment] 2016-06-09 17:29
@cbelden I think we might have to roll back your PR if this is breaking people. I didn't realize
it was a breaking change. Any idea when the new loader might support multiple calls to load()?

**Comment by fmauNeko** [comment] 2016-06-09 17:37
Apparently it's already in progress, as the upcoming version already supports them, even though the callbacks aren't called correctly. I wonder if there would be a way to test if the google.visualization object is the right one before resolving the promise (line 137).

**Comment by cbelden** [comment] 2016-06-09 19:09
It looks like the team plans to release a fix June 13th (version 45). Rolling back until then is probably the right call.

**Comment by jongeho1** [comment] 2016-06-10 11:47
👍  seeing same behavior when using multiple chart types together. fixing to 1.0.4 mitigates.

**Comment by ebidel** [comment] 2016-06-15 19:03
@cbelden can you confirm if the charts fix is in place? If it is, do we need to do anything here?

**Comment by ebidel** [comment] 2016-06-15 19:08
Going to close this as I think it's fixed. Please reopen if you see otherwise.

**Closed by ebidel** 2016-06-15 19:08 UTC

**Comment by php4fan** [comment] 2020-02-12 16:56
This is not fixed.

Multiple calls to `google.charts.load()` result in the bogus error message:
```
VM2232 loader.js:242 Uncaught (in promise) Error: Cannot load different versions of Google Charts
```
even though I'm calling load multiple times with the **same version**.

The behavior I expect is:
- if I call load again with the same version but a different set of packages, then the packages that have not been already included by the first call should be loaded by the new call.
- If I call it with the same version with the same packages (or a subset of the union of the packages included in all previous calls), then the call should be ignored.

At the very least, I would expect the error message to not be bullshit. For example "Cannot load the same Google Charts packages multiple times. Package xxxx already loaded". Or whatever.
Not that that would be acceptable, but at least I wouldn't waste extra time figuring out what is actually wrong.

**Comment by php4fan** [comment] 2020-02-12 17:18
Turns out I was accidentally loading **different languages**.

The error message needs to be more explicit.

**Comment by rslawik** [comment] 2020-02-14 09:01
This error comes from the Google Charts library. Please file the issue in [google/google-visualization-issues](https://github.com/google/google-visualization-issues) repo.

I tried to reproduce it with the following:
```
<script src="https://www.gstatic.com/charts/loader.js"></script>
<script>
  google.charts.load(47);
  google.charts.load(45.2);
</script>
```
or few variants, but I couldn't get any error. Could you share your steps?
